  #import "/temp/temp.typ": *

// ─── Settings ────────────────────────────────────────────────────────────────
#let courseid   = "AI505"
#let coursename = "Optimization"
#let term       = "Spring 2025"
#let dept       = "Department of Mathematics and Computer Science"
#let university = "University of Southern Denmark, Odense"
#let authors    = "Simon Holm, Johannes Rothe"
#let assnr      = "1"
#show: word-count
// ─── Page layout ─────────────────────────────────────────────────────────────
#set page(
  paper: "a4",
  margin: 2.7cm,
  header: context {
    set text(size: 10pt)
    if counter(page).get().first() == 1 {
      grid(
        columns: (1fr, auto),
        align: (left + horizon, right + horizon),
        [#dept \ #university],
        [#datetime.today().display("[day] [month repr:long] [year]") \ #authors],
      )
      v(-6pt)
      line(length: 100%, stroke: 0.4pt)
    } else {
      align(right)[#authors]
      v(-6pt)
      line(length: 100%, stroke: 0.4pt)
    }
  },
  footer: context {
    line(length: 100%, stroke: 0.4pt)
    v(-6pt)
    align(center)[
      #set text(size: 10pt)
      Page #counter(page).display() of #counter(page).final().first()
    ]
  },
)

#set par(
  justify: true,
  leading: 0.52em,
)


// ─── Typography ───────────────────────────────────────────────────────────────
#set text(font: "New Computer Modern", size: 11pt)
#set par(leading: 0.65em, spacing: 2em, first-line-indent: 0pt)

// Number equations
#set math.equation(numbering: "(1)")

// Section numbering
#set heading(numbering: "1.1")

// ─── Algorithm block helper ───────────────────────────────────────────────────
#let algorithm(caption: none, body) = {
  set text(size: 10pt)
  block(
    width: 100%,
    stroke: (top: 1pt, bottom: 1pt),
    inset: (x: 8pt, y: 6pt),
  )[
    #if caption != none [
      *Algorithm:* #caption \
      #line(length: 100%, stroke: 0.4pt)
      #v(-16pt)
    ]
    #body
  ]
}

// ─── Title ────────────────────────────────────────────────────────────────────
#v(-4pt)
#align(left)[
  #text(size: 11pt)[#courseid -- #coursename]
  #v(0.2cm)
  #text(size: 14pt, weight: "bold")[
    Answers to Obligatory Assignment #assnr, #term
  ]
  #v(0.4em)
  #line(length: 100%, stroke: 0.8pt)
]


// ─── Task 1 ───────────────────────────────────────────────────────────────────
#pagebreak()

= Task 1
== Problem Setup
=== Initial problem
A robot must move from a given start position to a given goal position in a 2D environment while avoiding obstacles and producing a smooth trajectory.

Since the trajectory is defined as
$ {x_1,x_2,dots,x_n} in RR^2. $

Lets fix 2 points, that is the starting point $x_1$ and the goal point $x_n$

$ x_1 = vec(1,1), quad x_n = vec(100,100). $

For this one can define a class in python to handle the search space. This way, whenever any a good path $x in RR^2 $ is found, the search space trajectory is updated.

=== Straight path
The straight path is generated by spacing a number of steps in a straight line from point $x_1$ to $x_n$. So for 100 steps. $x = [(1,1),(2,2),(3,3),dots,(99,99),(100,100)]$.

=== Obstacles

Obstacles can defined as a new structure to the environment, this way it is very convenient check for collisions.
All obstacle is defined as a circles with a center-point, and a diameter.
#figure(
  [example: `circular_object(c=[40,30], d=20.0)`]
)

#pagebreak()
=== Visualization
Using the python package `matplotlib`, the environment can be visualized along with the obstacles within and the trajectory $x$
#figure(
  image("assets/init_100s.png", width: 20em),
  caption: [Linear path with tree obstacles\
   `[circular_object(c=[40,30], d=10.0), circular_object(c=[60,70], d=20.0)` ]
)

It is notable, that there were some implementation issues, regarding trajectories that went straight through the center of obstacles, as shown in @problem
#figure(
  image("assets/problem.png", width: 20em),
  caption: [Issue regarding straight trajectories passing the center of obstacles]
)<problem>
This was easily fixable by adding a tiny bit of noise to the position of points in the initial straight line.

#pagebreak()

== Objective Function

The objective function is defined as
$ f(bold(x)) = f_L (bold(x)) + lambda dot f_S (bold(x)) + mu dot f_O (bold(x)) $

This function is then implement by the following definitions:

- Path length
  - $f_L (bold(x)) = summ(i=1, n-1, norm(x_(i+1) - x_i)^2) $

- Path Smoothness
  - $f_S (bold(x)) = summ(i=2, n-1, norm(x_(i+1) - 2x_i- x_(i-1))^2) $

- Object avoidance
  - $f_O (bold(x)) = summ(i=1,n,phi(x_i))) $
  - the avoidance function can be defined in multiple ways.
    + $phi_1(bold(x)_i) = mycases(
  1/((d(x)-r)^2), d(x)> r,
  oo, d(x)<= r,
  word: "if") quad #[for $i = 1,dots,n$] $
    + $phi_2(bold(x)_i) = exp(-alpha(d(bold(x)_i)^2 - r^2)) $

By testing both penalty functions, the 2nd penalty $phi_2$ function produce significantly better results. While the 1st penalty function $phi_1$ acts as a kind of barrier, penalizing $oo$ when a path touches an obstacles. While this on one hand could ensure that no part of the trajectory hits an obstacle, the smoothness and differentiability of $phi_2$. The issue $phi_1$ is the jump as a point touches an obstacle. For a point close to an obstacle, a small change in $x$ might result in a huge change in $phi$.

== Optimization Problem
Now to optimize the path $x$ so that the objective function $f(x)$ is minimized$ min_(x_2,x_3,dots,x_(n-1)) f(x). $

#pagebreak()
= Optimization Algorithms
To solve the given task, we implemented a range of optimization algorithms. Our group already had a solid understanding of which methods. Particularly first-order algorithms like gradient descent (and variations) are likely to perform well, given that derivatives are available while Hessians are computationally expensive to compute given a more complex trajectory.

For learning purposes, we also tested some less "optimal" methods (both 0th and 2nd) to explore trade-offs in convergence speed, stability, and computational limits.

== Gradient descent
The motivation for using 1st order methods while second order derivatives is available stems more or so directly from scalability. While second order derivatives are computationally expensive when the step-size of the trajectory is increased, 1st order derivates are much more scalable, because of this Gradient descent was implemented.


The basic gradient descent update is given by
$ x_(k+1) = x_k + alpha nf(x_k). $<GD>

#figure(
  image("GD_100steps_1000iter.png"),
  caption: [Gradient descent with a fixed $alpha>0$]
)<GDplot> 


where $alpha > 0$ is a fixed step size. @GDplot illustrates the resulting trajectory over 1000 iterations. While the method converges, the rapid convergence shows how a fixed step-size $alpha$ can be be tuned to a specific landscape, while in others, it might not perform as well. 

#pagebreak()
=== Line Search for Step Size
@GDplot creates the motivation for replacing the fixed $alpha$ with a per-iteration line search.
This is done by strong bracketing - line search
#figure(
  image("GDSB_100steps_1000iter.png"),
  caption: [Gradient descent, now using strong bracketing - line search to find a new step-size each iteration]
)<GDSBplot>

The rightmost plot (@GDSBplot) tracks $alpha$ across iterations of the Gradient Descent using line search, illustrating
how the line search adapts the step size dynamically rather than relying on a
hand-tuned constant. The oscillatory behavior in $alpha$ is likely due to the Armijo-conditions being satisfied.




Lets compare the two convergences, and zoom in a bit

#figure(
  grid(
    columns: 2,
    gutter: 1em,
    image("conv1.png",width: 19em), image("conv2.png",width: 16.8em),
  ), caption: [_Left_: Convergence of basic gradient descent. _Right_: Convergence of gradient descent with line search]
)
The line-search-modification method is notably slower per iteration, but in theory it should converge more reliably. From testing, it seems that there are minor difference in convergence. It seems that while the strong bracketing, is more sure about the steps its making, it does take longer to find a minimum. So while the line search method might be good for control, it still needs more than 1000 iterations of training to get event close to what the gradient descent can achieve in just 50 iterations

== Accelerated descents
Even though the gradient descent performs well, there are other methods which might be suitable for this problem. The following methods are implemented and compared, as their differing mechanics are of independent interest.





#figure(
  image("GDM_100steps_1000iter.png"),
  caption: [Gradient Descent with Momentum\ #v(0em)
            $ x_(k+1) = x_k + v_(k+1)\
            v_(k+1) = beta v_k - alpha nf(x_k).$]
)<GDMplot>

@GDMplot depicts the Gradient descent with momentum. Momentum is applied to each a minimum faster, by trying to replicate the physical momentum. Its clear that while this method does converge, it reaches a convergence much slower. This gives motivation for Nesterov Momentum, since it generally reaches a better optimum in the same amount of iterations.

#figure(
  image("GDNM_100steps_1000iter.png"),
  caption: [Gradient Descent with Nesterov Momentum\ #v(0em)
          $ x_(k+1) = x_k + v_(k+1)\
          v_(k+1) = beta v_k - alpha nf(x_k+beta v_k). $]
)

The Nesterov Momentum method does indeed reach a convergence much faster than just momentum. While the trajectories looks very alike, comparing two parts of the trajectory shows exactly what makes the Nesterov momentum method superior. Nesterov slows down (due to the look-ahead $beta v_k$) as the $x$ gets closer to $x^*$. This way its less likely that the descent overshoots

#figure(
  grid(
    columns: 2,
    gutter: 1em,
    image("nestmov.png",width: 19em), image("mov.png",width: 19em),
  ), caption: [_Left_: Gradient Descent with Momentum. _Right_: Gradient Descent with Nesterov Momentum. ]
)<momVSnest>
The difference between nesterov momentum and the regular momentum is visually shown in @momVSnest, where its quite obvious that the regular momentum overshoots, where the nesterov doesn't.

#pagebreak()

It seems that neither line search nor momentum alone improves on the gradient descent. While the line search modification gives control over the learning rate, its very slow in convergence. And while nesterov momentum converges very fast, it lacks the control of step-size that line-search gives. The fix: use both.

One can implement another algorithm that takes both nesterov momentum, and calculates the step-size using line-search



#figure(
  image("GD_mix_100steps_1000iter.png",width: 30em),
  caption: [Gradient Descent with Nesterov Momentum and Line Search with $100$ steps and $1000$ iterations]
) <GDNMSBplot>
@GDSBplot illustrates the optimization trajectory and convergence of a hybrid approach that combines Nesterov momentum with line search, providing both rapid convergence and controlled step-size selection.


The Adam optimizer (_adaptive moment estimation_) achieves a similar goal to line search combined with momentum, where it while using momentum, adapts the leaning rate to each parameter
#figure(
  image("GDadam_100steps_1000iter.png",width: 41em),
  caption: [Gradient Descent with Adam with $100$ steps and $1000$ iterations]

)<adam>
This achieves an even better trajectory, while using both momentum and an adaptive learning rate. The _rightmost_ diagram, depicts the different learning rates for each parameter in the optimization process as well as how they adapt. The diagram only depicts the `min`, `mid` and `max` learning rate, since $x in RR^2$ of length 100 has 200 parameters.

== Newton method
After implementing the newtons method, it was observed that the algorithm didn't converge, but taking steps in a seemingly random direction, thereby increasing the function value to extreme amounts within a few steps. Consulting the theory, it seemed that if the starting point is sufficiently far away from the optimal solution. A version to solve this is to modify the hessian using Algorithm 3.2 (Line Search Newton with Modification) of @book with line search based on the strong wolfe conditions. 
This required the hessian matrix to be factorized:

$ B_k = nabla^2f(bold(x)_k) + E_k $

Where $E_k = 0$ if the hessian is sufficiently positive definite. A simple way to do this is to modify the hessian as follows: 

$ nabla^2f(bold(x)_k)= Q Lambda Q^T $
Where $Q$ are the eigenvectors, and $Lambda$ is a diagonal matrix with the eigenvalues as it's entries. Then the rest of the algorithm was implemented, and converged as follows:

#figure(
  grid(
    rows: 2,
  image("newt1.png"),
  image("newt2.png")
  ),
  caption: []
)
Here it can be observed that path becomes pushed almost into a single point. This is due to the way to problem is structured. To minimize the different functions, moving the points close together, would mean that a potential deviation in for example the average distance between the points would be even smaller. Also because of how the code is structured, after each new path, the start and end points are removed from the sequence so the model doest move them to optimize the goal. This does however mean that any penalty between the start point and the second point is not registered. A revised version of this problem could be expressed as the segments between the points should count in avoidance, but the limited time scope of this project sadly does not allow it.


== Nelder Mead

As mentioned earlier, even though the first-order methods perform really well, it is very much of interest to try and implement some other  interesting methods, in particular the Nelder Mead method. The "Nelder-Mead Simplex Method" is a vastly different method compared to those previously discussed, since it is a derivative free method, and only work my doing many function evaluations. Since simple function evaluations are on $cal(O)(n)$ time, the Nelder Mead method is extremely fast per iteration compared to the preciously discussed methods which are either first order or second order. The "0th" order does have its drawbacks as the Nelder Mead method needs way more iterations than other methods.

#figure(
  image("nelder.png"),
  caption: [Nelder Mead Simplex Method, with $50$ steps with $50.000$ iterations]
)<nelder>

The Nelder Mead method on @nelder is inherently suboptimal for this problem, as it does not make use of gradient information at all. Since gradients are easily available for this problem, one should opt to utilize them, as provide valuable local information about the objective.

#pagebreak()
=== Comparison
Comparing methods with each other, can give a good perspective, on where some methods works better than other. Comparing across hyperparameters such as number of steps, and iterations and time, can give good insight into each methods strengths and weaknesses. The objective function's hyperparameters, such as the avoidance factor and path length weighting, have been tuned to suit the environment and are then fixed across all methods, ensuring every optimizer is evaluated on the exact same problem. Each method's own hyperparameters have likewise been tuned to perform well for that specific method. The details of the tuning are omitted here, as they're not central to the comparison.

So far all algorithms has been tested on a max iterations limit, however since many of the algorithms differ in the time one iteration takes, it also makes sense to compare these algorithm on another stopping criterion. The following figure compares how the number of steps in a trajectory can change the behavior of a method. For this, the stopping criterion is fixed to 10 seconds. By fixing a time limit, the slower algorithms needs to perform better per. iteration than faster algorithms. This ensures that the only relevant factor is the method them selves.

#figure(
  grid(
    rows: 5,
    gutter: 1em,
    image("compare10steps_10sec.png"),
    image("compare25steps_10sec.png"),
    image("compare50steps_10sec.png"),
    image("compare100steps_10sec.png"),
    image("compare200steps_10sec.png"),
  ), caption: [Comparing all models on number of steps given 10 seconds of training time ]
)<steps>
#pagebreak()
The results on @steps are interesting. Its clear that the performance of these method greatly depends on how the amount of steps in the trajectory. The amount of steps correlates directly to how complex the search-space becomes for the algorithm, so under a fixed computational bound like 10 seconds, algorithms requiring fewer iterations to converge dominate. This gives good motivation to test each algorithm in regards to the iterations. Lets fix a step length of 50 (since it looked optimistic in $@11$) and test each method over $10, 50, 100, 250, 500$ and $1000$ iterations.

#figure(
  grid(
  rows: 6,
  gutter: 1em,
  image("compare50steps_10iter.png"),
  image("compare50steps_50iter.png"),
  image("compare50steps_100iter.png"),
  image("compare50steps_250iter.png"),
  image("compare50steps_500iter.png"),
  image("compare50steps_1000iter.png")
), caption: []
)<iter>


Like mentioned earlier it is evident that giving more time to the methods which have worse performance at high complexity, will enable them to also reach a good trajectory. For most of the methods it seems that $apx 500$ iterations will almost always produce a converging trajectory. It is notable that the `Nelder_Mead` method is much faster per. iteration and therefore needs many more iterations so converge. 

#pagebreak()
Since the cost per iteration varies significantly between methods, comparing them under a fixed step budget can bias the results in favor of methods with fast per-iteration convergence, while penalizing those that require more expensive updates but may ultimately reach better solutions. To investigate how they converge further, lets go back to using time as a stopping criterion but now fix steps. It would be of interest so see how the different methods converge based on how much training time they have done. Lets test for $1, 10, 30, 120$ and $300$ seconds. This way every algorithm hopefully converges.

#figure(
  grid(
  rows: 4,
  gutter: 1em,
  image("best_1sec.png"), // replace
  image("best_10sec.png"), // replace
  image("best_30sec.png"),
  image("best_120sec.png"),
  image("best_300sec.png")
), caption: [`Gradient_Descent`, `Gradient_Descent_Line_Search`,\ `Gradient_Descent_Nesterov_Momentum`, `Gradient_Descent_Momentum`\ , `Gradient_Descent_Nesterov_Momentum_Line_Search`, `Gradient_Descent_Adam` and `Nelder_Mead` compared against each other on time: `1, 10,30,120` and `300` seconds]
)<time>
@time depicts the methods once again, this time test only on the time. Where as most of the gradient descent variations needs $apx 50\-250$ iterations to converge, the Nelder Mead reaches over  $500.000$ iterations.

#pagebreak()

=== SciPy comparison

It is very valuable to compare the so-far explored methods with some kind of benchmark. To put thir performance into perspective, lets also compare them against the corresponding minimizers from SciPy's `scipy.optimize` library. The SciPy implementations are mature, well-tested, and widely used, so if our implementations perform comparably, it serves as a strong validation that they are correctly implemented and behave as expected.

Lets first compare the Gradient Descent using an implemented line search (with strong bracketing) with `scipy.optimize.line_search`. This replaces the line-search which is implemented using strong bracketing (satisfying strong wolfe conditions) just like `scipy.optimize.line_search`. So in theory these should result in near-similar performance

#figure(
  grid(
    rows: 2,
    image("GDSB_100steps_1000iter.png"),
    image("GDSB_scipy_100steps_1000iter.png")
  ), caption: [_Upper_: Gradient descent using line search implemented by the authors\
_Lower_: Gradient descent using line search provided by `scipy.minimize`]
)<lineserachcompare>

As shown on  @lineserachcompare, the SciPy implementation does have minor performance difference compared to the implementation by the authors most visibly shown on the more stable $alpha$-values, however as performance goes, it seems that these two implementation are near-identical, validating the correctness of the authors' implementation. The most notable difference beside this its the computational speed, as SciPy's implementation is quite faster.

#pagebreak()
Again using SciPy, lets now compare some of the best methods, to a general benchmark minimizer from `scipy.minimize`. `L-BFGS-B` (_Limited-memory Broyden–Fletcher–Goldfarb–Shanno with Box-constraints_) was selected from SciPy's local minimization solver comparison table as a representative general-purpose benchmark #link("https://docs.scipy.org/doc/scipy/tutorial/optimize.html#local-minimization-solver-comparison")[*[link]*] @scipybib

#figure(
  gap: 2em,
  grid(
    rows: 2,
    columns: 2,
    column-gutter: 1em,
    row-gutter: 1em,
    figure(image("GD_100steps_1000iter.png",width: 20em),caption: [Basic GD]),
    figure(image("GDNM_100steps_1000iter.png",width: 20em),caption: [GD and Nesterov Momentum]),
    figure(image("adam2.png",width: 19em), caption: [GD with Adam]),
    figure(image("SciPy_min.png",width: 22em),caption: [SciPy implementation of `L-BFGS-B` ])
  ), caption: [Comparing best performing methods with SciPy benchmark.]
)<lbfgsb>

@lbfgsb presents a comparison of a selection of methods considered by the authors to be strong candidates for this problem, evaluated against the SciPy `L-BFGS-B` benchmark. Note here that while @lbfgsb includes the basic Gradient Descent, its not preferred to the others, since it does not utilize neither momentum, adaptive learning rates, however its still of interest to compare to the better more utilizing methods. Besides this the results are highly promising, though they might indicate that this optimization problem has a performance ceiling.  If a problem is relatively simple, then a good method, might perform perfectly while failing in a more complex environment.
#pagebreak()
=== Different environments

To further demonstrate the capability of one of the moste promising methods method, it is evaluated across a range of environments of varying complexity. 

#figure(
  grid(
    rows: 2,
    columns: 2,
    image("env1.png"),
    image("env2.png"),
    image("env3.png"),
    image("env4.png")
  ),caption: [Gradient Descent with Adam in different challenging environments]
)<adamdif>

On @adamdif, Gradient Descent with Adam is depicted in $4$ different with $100$ steps and $1000$ iterations 

// ─── Task 2 ───────────────────────────────────────────────────────────────────
#pagebreak()
= Task 2
== Baseline
To have a comparison for how good the optimization on the problem is, the starter code is tested on a machine, and yields the following loss and test accuracy after 10 epochs:
\
Test set: Average loss: 0.0172,         Accuracy: 5953/10000 (59.5299%)

Throughout the report, the standard for what is a better model will be the accuracy it achieves. A loss is hard to compare to actual performance, and if this was a real world case where a model had to be developed, it would be what was actually important.




== Basic and Batch SGD
The given starter code, it is very easy to modify to accommodate either basic SGD by setting the batch to 1, or to run Batch SGD where the batch size is set to the full training set (60,000). 

=== Batch SGD:
Training with a batch size of 60,000 is a lot more computationally expensive, which is usually leveraged with either parallel processes, or second-order methods. Deep learning is a notorious non-convex problem, so having the possibility to do second-order methods is not guaranteed to decrease the test loss and accuracy. Using batch SGD without changing other parameters leads to the following loss/accuracy after 10 epochs:
\
Test set: Average loss: 0.0002,         Accuracy: 1236/10000 (12.3599%) 

This is however not a good representation for batch training, since the full knowledge of the entire function is not properly utilized. This will be addressed in @second-order-methods. 

=== Basic SGD:
Basic SGD, which uses a batch size of 1, yielded significantly better initial convergence.  This was again simply implemented by modifying the basic code to have a batch size of 1.
\
Test set: Average loss: 0.3060,         Accuracy: 8917/10000 (89.1699%)

This performance can also be explained in the amount of steps, or gradient updates. For 60,000 pictures, with a batch size of one, 10 epochs with basic SGD updates the gradient 600,000 times, wheres Batch SGD only updates 10 times. Basic SGD's drastic increase in performance will theoretically slow down, since it updates on each picture at a time, the amount of noise will make it hard for it converge to an optimum for the entire problem (the 60,000 pictures). 

#pagebreak()
== Momentum and other optimizers
To improve the performance of algorithm, a host of different optimizer algorithms from the torch.optim was implemented. This included:
- SGD with momentum
- AdamW 
- NAdam
- AdaGrad
- RMSprop
- Adadelta
- Adam
- The second order method LBFGS which will be discussed further in section @second-order-methods

This was done to get an overview of which of the standard optimizers work well for the given optimization problem, and thereby which should be further worked on.

#figure(
  image("Comparision_of_ALL_Models.png"),
  caption: [Comparison of different optimizers on 100 epochs]
)<all_models_comparision>

Here it was observed that a few different models performed well, and in different areas. Ada and Adam based models converge quicker than less dynamic methods such as classic SGD. However, the more dynamic methods were more prone to overfit on the training data, and thereby lead to a increase in the test loss, and a reduced accuracy. This means that models such as AdamW converge quickly, and with the right regularization and noise techniques, therefore has more time to converge to a better minium. Whereas SGD, that isn't as prone to overfitting, can be trained a lot longer without the risk of overfitting. 

To find the optimal solution, three different paths will be further developed:
- Using AdamW to converge quickly within 10 epochs
- Using AdamW to converge to optimal solution with regularization
- Using SGD to converge to optimal without regularization

Each of the following methods can then be further optimized with their parameters such as learning rate and momentum, but other techniques to reduce noise will also be used. 

== Getting AdamW to converge quickly
To optimize AdamW to converge quickly, it can be tested with different parameters, to find the one that converges the fastest. Afterwards, different noise reduction techniques will be applied to optimize even further. 
\
=== Optimizing the learning rate

#figure(
  image("Comparing_AdamW_LRs_30_epochs.png"),
  caption: [Comparison of different learning rates for AdamW]
) <AdamW-learning-rate>
The figure shows a clear trend towards smaller learning rates. AdamW is an adaptive momentum model, meaning it changes the learning rate during the training. Making the learning rate to high, will make it more unstable. This can be seen with the larger learning rates not only performing worse, but also being more unstable and having bigger jumps.
=== Optimizing the batch size 

#figure(
  image("Comparing_batchSizes_AdamW.png"),
  caption: [Comparison of different batch sizes for AdamW with lr=0.001]
) <AdamW-batch-size>
Here it can be seen that a smaller batch size of around 16 is ideal for converging early.


== Getting AdamW to converge to optimum
=== Testing different weight decay
Getting the AdamW optimizer to converge not the fastest, but to the best optimum, requires changing the strategy. A smaller batch size would introduce more noise, and from @AdamW-batch-size it can be seen that in longer trainings, a batch size of 256 achieves a better performance. Having a smaller step size is only beneficial in terms of reducing noise, so the previous value of $0.001$ will be kept.

Next, weight decay values will be tested for AdamW, to make sure it doesn't overfit:
#figure(
  image("Comparing_Different_wd_for_adamW_lr=0.001.png"),
  caption: [Comparison of different weight decay values for AdamW with lr=0.001 and batch size of 256]
)<wd_for_AdamW>
Here it can be observed that a weight decay value of 0.1 is optimal

== Getting SGD to converge to optimum
To find the optimum using SGD, the initial parameters like learning rate and momentum have to be optimized for. 

=== Optimizing the learning rate
First the learning rate is optimized for, by testing different optimizers, with the only variable being the learning rate:



#figure(
  image("Comparing_Different_lr_for_SGD_mom=0.9.png"),
  caption: [Comparison of different learning rates for SGD with momentum=0.9]
) <SGD-learning-rate>

Here it is clearly observed that a learning rate of $0.001$ performs the best.

=== Optimizing the momentum
After finding the optimal learning rate, it was fixed, and then a set of different momentums was tested for:

#figure(
  image("Comparing_Different_Momentums_for_SGD_lr=0.001.png"),
  caption: [Comparison of different momentums with a learning rate of 0.001]
)<sgd_momentum>
Here it was found that a momentum of 0.95 was optimal.

=== Optimizing the batch size

#figure(
  image("Comparing_batchSizes_SGD.png"),
  caption: [Comparison of different momentums with a learning rate of 0.001]
)<SGD_batch_size>
Here the data was very noisy, so its hard to clearly determine which batch size is best suited. But the more general size of 64 was decided to best the best overall.

== Noise reduction
To reduce noise in the training phase, the use of noise reduction techniques was decided to be implemented. Choosing from the provided theory gave 3 main choices:
- Dynamic Sampling
- Gradient Aggregation
- Iterate Average

For this problem, dynamic sampling was used because it was the only one that wasn't extremely dependent on the function to be convex (A Lipschitz assumption could be used to create some sort of guarantee, but finding a Lipschitz constant of a highly non-convex and non-linear seemed almost impossible) and could still provide a theoretical improvement in noise reduction. A git hub repository was used to implement step-wise increment to the batch size, which also meant that a $tau$ variable could be set. The found $tau$ values was set during experimentation as it's hard to give a definitive answer to a optimal $tau$ value, without putting it in relation to the problem. 
\
The StepBS algorithm works by being able to set after how many steps the batch size should be modified by some $gam$. For the following tests, $gam$ was set to 2, and then the steps was updated after each epoch. So a StepBS with step 10, would mean that the batch size would double every 10 epochs.

=== Dynamic sampling on the optimal models
==== Fast converging AdamW
#figure(
  image("Comparing_StepBS_AdamW_withStartBS=16.png"),
  caption: [Comparison of StepBS $gam$ values for fast AdamW]
) <dynamic-sampling-fast-adamW>
Here it is quite clear, that a batch size value that doubles every 2 epochs performs the best. 
==== Optimal solution AdamW
#figure(
  image("Comparing_StepBS_AdamW_withStartBS=256.png"),
  caption: [Comparison of StepBS $gam$ values for optimal AdamW]
)<dynamic-sampling-optimal-adamW>
The data for dynamic sampling with an optimal model is quite noisy, so it's hard to argue definitively if no sampling, or a doubling every 10 epochs is best. Since this is only 30 epochs, and a optimum could be found after many more, it was decided that the dynamic sampling that doubles the batch size every 10 epochs would be chosen.
==== Optimal solution SGD
Here dynamic sampling was used on the optimal solution of SGD:

#figure(
  image("Comparing_StepBS_SGD_StartBS=64.png"),
  caption: [Comparison of StepBS $gam$ values for optimal SGD]
)<dynamic-sampling-optimal-SGD>
Here the data is also very noise, so it's hard to definitively say that one performs better than the other. It was decided that no dynamic sampling would be used since in. previous tests SGD converged quite well, even on many epochs, and using dynamic sampling might "flatline" the convergence to early. Although given more time, both options could be tested.
#pagebreak()
=== Learning rate schedulers
Another method used to optimize against noise is some kind of learning rate scheduler. Using a learning rate scheduler its much easier adapting the learning rate to the environment (and the task), opposed to fine tuning some very specific fixed learning rate. By using a scheduler, the learning rate instead changes over epochs, for a more dynamic training. There are many different scheduler great for different purposes. Each methods using a different kinds of learning rate decay $eta_(t+1) <- eta_t dot #[something]$
#figure(
  grid(
  columns: 3,
  figure(
    image("factor_scheduler.png"),
    caption: [Simple factor decay]
  ),
  figure(
    image("cosine_scheduler.png"),
    caption: [Cosine decay]
  ),
  figure(
    image("warmup_cosine_scheduler.png"),
    caption: [Warmup + \ Cosine decay]
  )
), caption: [different learning rates examples @divedeep]
)
While all of the above might work well, after testing, the warm up scheduler shows to outperform the others. Cosine decay might have a generally slower convergence than something simple as a factor decay, since it opts to not drastically decreasing the learning rate at the very start. Instead it "refines" the optimization process later on. The only drawback of this is the initial high learning rate. This can be optimized using the warmup. With warmup the learning rate start out making sure the optimization is on the right path, before encreasing the learning rate and then doing cosine decay. This works really well in many scenarios, as well as this problem. Furthermore, based on prior work, this approach has been found to work reliably. 

#pagebreak()

=== Learning rate scheduler annealing on the optimal models
Now lets test the warmup cosine scheduler on the otherwise optimal methods.

==== Learning rate scheduler annealing on models <simAdamW>
#figure(
  image("Comparing_SA_for_AdamW_16.png"),
  caption: [Comparing Scheduled learning for fast converging AdamW]
)<simulated_annealing_for_adamW_16>
#figure(
  image("Comparing_SA_for_AdamW_256.png"),
  caption: [Comparing Scheduled learning for optimal AdamW]
)<simulated_annealing_for_adamW_256>


#figure(
  image("Comparing_SA_for_SGD_64.png"),
  caption: [Comparing Scheduled learning for optimal SGD]
)<simulated_annealing_for_SGD_64>

In both instances of AdamW as well as the optimal stochastic gradient descent, most of the models perform reasonably well alongside the control. For the optimal AdamW and the optimal stochastic gradient descent, the result does not differ much, however in the case of the fast converging AdamW, the models seems to perform better without learning scheduler 

== Second-order Methods <second-order-methods>
Second order methods have the power to leverage a lot more information, typically in the form hessians to use this to converge in a reduced amount of steps (Not necessarily time, since each step is more computationally expensive). To test the viability of second order methods, the quasi-newton method L-BFGS was used to to it's ability to use limited memory, and therefore being possible to run on smaller machines. As well as being a quasi-newton ensures that it doesn't have to compute the exact hessian, but only an approximation. This makes L-BFGS a good suit for this large scale unconstrained optimization problem. 

For this project, L-BFGS was implemented with strong wolfe conditions. Because as a default, L-BFGS, as other second-order methods use a step size of one due to it's nature of finding the optimal direction. By introducing strong wolfe conditions, it ensures that the optimizer doesn't end up overshooting the target, and therefore not being able to "get back" and find the minimum. This occurred during the initial testing phase.

The L-BFGS ended up being quite unreliable, with its range of accuracy after 10 epochs being between 10-88% (usually withing 70-86%), thereby making the optimizer quite vulnerable to the starting conditions.

This vulnerability and unpredictability about whether the model will even converge was the reason for this project that it was not used.

== Optimal Models

The final found optimal models will now be tested, to see which performance is achieved.
=== Fast convergence
#figure(
  image("Testing_fast_AdamW.png"),
  caption: [Comparison between fast converging AdamW and base SGD]
)
Here, the fast AdamW can be seen to converge around the first 6 epochs.
\
The fast converging AdamW has the following result:
Test set: Average loss: 0.0174,             Accuracy: 8982/10000 (89.8199%)

And the base model SGD has the following result:
Test set: Average loss: 0.0376,         Accuracy: 7612/10000 (76.1200%)

Showing that the AdamW is vastly superior.
=== Optimal solution
#figure(
  image("Comparing_Optimal_Models_150_epochs.png"),
  caption: [The 2 optimal models (with and without regularization) with 100 epochs]
)
==== Standard Cross-Entropy Loss
SGD After 100 epochs: Test set: Average loss: 0.0055,         Accuracy: 8976/10000 (89.7600%)
\
Base case after 100 epochs:
Test set: Average loss: 0.0068,         Accuracy: 8419/10000 (84.1900%)


From this it can be concluded, that the optimal model of SGD without regularization performs significantly better than the base model.
==== Regularized Cross-Entropy Loss
AdamW after 100 epochs: Test set: Average loss: 0.0011,         Accuracy: 9035/10000 (90.3499%)
\
Base case after 100 epochs:
Test set: Average loss: 0.0068,         Accuracy: 8419/10000 (84.1900%)

Again here the found optimal model performs significantly better than the base model.

#pagebreak()
== Discussion
Although not everything in the project can be exploitively attributed to theory, there is some trends that show up, hinting to the underlying and methods, when and why they should be used.

For finding the optimal fast converging AdamW, we see a trend that points bold strategies. Having the learning rate low is to be expected, as AdamW uses adaptive momentum. By having a lower initial learning rate, it has an easier time fitting to the correct parameters as seen with @AdamW-learning-rate. This same trend can be seen with @AdamW-batch-size. By having the batch size at the lower range with for example 16, it enables it to compute more gradients within the first few epochs, thereby converging quicker. Since it is more stochastic than larger batch sizes, the steps might not be in the most optimal way, but it compensates for that with lots of updates instead. This trend continues for dynamic sampling, where in @dynamic-sampling-fast-adamW a smaller step size (leading to a larger $tau$ value) yields better results. By having the batch size small at the start, it manages to quickly move in the correct direction, and with quickly increasing it to larger batch sizes, it manges to converge more accurately later. This might be why as shown in @simulated_annealing_for_adamW_16, using a learning rate scheduler doesn't have an impressive benefit. The previously mentioned parameters and noise reduction techniques already achieves these goals.

Finding the optimal solution for AdamW was about reusing some elements, and then optimizing for a different objective. Here since the objective was not to converge quickly, different batch sizes could be chosen. As seen in @AdamW-batch-size, a batch size of 256 converges much slower, but performs a lot better at later stages. This also fits with the theory that a larger batch size, will take more precise steps later in the training. Having settled on a batch size of 256, regularization could be tested. Here a relatively large weight decay was found to work better. Afterwards the model could be fine tuned with dynamic sampling and scheduled learning. 


The optimal solution for SGD with momentum was also found by first finding an appropriate learning rate. Here the learning rate $0.001$ found to be most optimal. @sgd_momentum shows a comparison of different momentum values, and its quite clear that momentum plays a significant role. The more momentum, the better the model performs. This could be because the momentum helps the optimizer move in the overall best direction, and doesn't get as easily pulled towards and in local minimums. A general batch was chosen to be able to converge better at later stages. Lower batch sizes might be able to converge quicker, but could struggle to optimize at the later stages due to the limited amount of points it optimizes on. 


=== Batch sizes
Trough this project, it has been observed that the batch size has had a significant effect. Batch optimization might be a lot slower to converge, since it needs to evaluate the entire dataset to take a single step, whereas stochastic variants can perform thousands of gradient updates within a single epoch. The obvious drawback is the amount of noise evaluating on a single data point at time makes it unlikely to converge to a great optimum. A good optimizer utilizes both of these strengths, using a small batch size at the start, and gradually increases towards the end. This is what is seen in the optimal models like AdamW that starts with a relative small batch size, but ends up using the entire dataset. 



=== Possible improvements
If case2 of the project was to be redone, there would be made some changes. Given more time, each run would be made 3 different times, and then the average would be taken. This would reduce a noise factor, that could have contributed to some optimizers/parameters being possibly wrongfully chosen. 
\
The complexity of the problem, made it hard to leverage relevant theory as much as was wanted from the group, but it nonetheless gave valuable experience in how complex optimization problems can be. 



== Conclusion
After deliberate and meticulous optimization trough mainly experimentation, final models was found that satisfied the given requirements and gave a reasonable performance. Models that converged to much better optimums, in significantly shorter time was achieved.




// ─── Appendix ─────────────────────────────────────────────────────────────────
#pagebreak()
#set heading(numbering: "A")
#counter(heading).update(0)
= Use of generative AI


#table(
  columns: (1fr, 1fr, 2fr),
  align: left,

  // Header row
  [*Phase*],
  [*AI use? Please check*],
  [*If AI has been used: How much of the task has been AI-enhanced? Please estimate AI co-authorship in percentages*],

  // Data rows
  [Literature reading and comprehension],
  [#h(1em) []],
  [],

  [Creating an argument structure for the text (skeleton outline)],
  [#h(1em) []],
  [],

  [Writing sentences],
  [#h(1em) [ ]],
  [],

  [Revising sentences],
  [#h(1em) [ ]],
  [],

  [Proof-reading (Grammar and Spelling checks)],
  [#h(1em) [x]],
  [For proof reading and gramma spelling AI has had co-authorship in 10 %.],

  [Other (What)],
  [#h(1em) [x]],
  [Generative AI has been used to the general construction and formatting of the paper such as the front page, margin, headers and footnotes. For this task AI has been co-author in about 70% % for this given task.
  Generative AI has been used sparsely for writing very repetitive code, as well as solving compilation errors @claude],
)

#bib("references.bib")
